#!/usr/bin/env sh
# tmux-style.sh — popup & picker style variables derived from tmux-colors.conf.
# Auto-generated by omarchy-theme-set — do not edit manually.
# Template: ~/.dotfiles/main/tmux/.config/omarchy/themed/tmux-style.sh.tpl
#
# Colors are read live from the tmux @options set by tmux-colors.conf so that
# this file never duplicates color definitions — tmux-colors.conf is the single
# source of truth.

_tget() { tmux show-option -gqv "$1" 2>/dev/null; }

# ── Popup appearance ──────────────────────────────────────────────────────────
TMUX_POPUP_BORDER_COLOR=$(_tget @POPUP_BORDER_COLOR)
TMUX_POPUP_TEXT_COLOR=$(_tget @POPUP_TEXT_COLOR)
TMUX_POPUP_WIDTH="80%"
TMUX_POPUP_HEIGHT="80%"

# ── Picker color spec (window-picker / sesh-picker) ──────────────────────────
_seg_bg=$(_tget @SEGMENT_BG)
_fg=$(_tget @FG)
_accent=$(_tget @ACCENT_COLOR)
TMUX_COLOR_SPEC="list-border:${_seg_bg},group-header:${_fg},selected-prefix:${_accent},selected-fg:${_fg}"
unset _seg_bg _fg _accent

# ── Spinner ───────────────────────────────────────────────────────────────────
# TMUX_SPINNER_NAME: dot, minidot, line, jump, pulse, points, meter, hamburger,
#                   ellipsis, globe, moon, monkey, arc, nerd, nerdarc
TMUX_SPINNER_NAME="minidot"
# TMUX_SPINNER_COLOR: used by --spinner-color and opencode-state.sh #[fg=...].
TMUX_SPINNER_COLOR=$(_tget @ACCENT_COLOR)

unset -f _tget
