[tui]
percentage = 30
min = 8
max = 20
restore_fullscreen = false

[ui.nav]
active = true
bar = "Plain"
color = "white"

[query]
status_inline = false
prompt = "> "
prompt_style.fg = "cyan"
prompt_style.modifier = "BOLD"

[status]
show = false

[footer]
content = " {cyan,bold:[Enter]} {darkgray:Confirm}  •  {yellow,bold:[Esc]} {darkgray:Back}"
row_connection = "Full"
match_indent = false
style.fg = "gray"
style.modifier = "DIM"

[exit]
allow_empty = true

[start]
ansi = true
mode = "standard"
output_template = "{=query}"

[start.command]
command = "echo ''"

[binds]
"enter" = "Accept"
"esc" = "Quit"
