[[wildcard]]
pattern = "~/dev/github/**"
startup_command = "agy"

[[wildcard]]
pattern = "~/.dotfiles/*"
startup_command = "agy"

[[session]]
name = " Downloads"
path = "~/Downloads"
startup_command = "wm -o jump"
